webitel/cc-workspaces

src/store/modules/call/client-handlers.js
src/store/modules/chat/client-handlers.js

Пофіксив багу, яку ти мені сьогодні кинув. 
Там логіка вся була вже, просто провтикали один екшон на відповідь
Кидаю ПР

fix: active call card opens automatically on auto-answer [WTEL-2360]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-text.vue

feature: wrapping userform text[WTEL-2749]

---

src/ui/hotkeys/useHotkeys.js

Why do we need to prevent default behaviour of keydown event?
All details in comments.
https://webitel.atlassian.net/browse/WTEL-4515

fix: prevent default behaviuor of hotkeys [WTEL-4515]

---

src/ui/hotkeys/HotkeysActiom.enum.js
src/ui/hotkeys/digitKeys.js
src/ui/hotkeys/useHotkeys.js
src/ui/modules/info-section/modules/processing/modules/form/components/the-processing-form.vue

Added hotkeys for buttons in processing form.
https://webitel.atlassian.net/browse/WTEL-4516

feat/add hotkeys on processing form buttons[WTEL-4516]

---

package-lock.json
package.json

fix: update ui-sdk [WTEL-5456]

---

package-lock.json

Reverts webitel/cc-workspaces#570

Revert "Fix/update package lock"

---

src/ui/modules/work-section/modules/chat/mixins/chatMessageFileMixin.js

(https://webitel.atlassian.net/browse/WTEL-6268)

fix: add to chat image computed verification is heic type [WTEL-6268]

---

package-lock.json
package.json
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-select-service.vue
src/ui/modules/info-section/modules/processing/modules/form/components/the-processing-form.vue

(https://webitel.atlassian.net/browse/WTEL-5667)

feature: add new component processing-form-select-service.vue [WTEL-5667] 

---

src/ui/modules/work-section/modules/chat/chat-messaging/components/chat-emoji.vue

(https://webitel.atlassian.net/browse/WTEL-6149)

fix: change chat-emoji.vue styles [WTEL-6149] 

---

src/main.ts

(https://webitel.atlassian.net/browse/WTEL-6764)

fix: remove const before already declared variable [WTEL-6764] 

---

src/ui/modules/info-section/modules/processing/modules/form/components/the-processing-form.vue

(https://webitel.atlassian.net/browse/WTEL-6794)

fix: change path to componentAction() form-table in sendTableAction method [WTEL-6794]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue

(https://webitel.atlassian.net/browse/WTEL-6795)

fix: add 'px' to width parameter in table header [WTEL-6795]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/api/table.js

(https://webitel.atlassian.net/browse/WTEL-6797)

fix: get data from table resp and add response handler to table api [WTEL-6797]

---

src/ui/modules/popups/disconnect-popup/components/disconnect-popup.vue

(https://webitel.atlassian.net/browse/WTEL-6860)

feature: add isDisconnect Sound Allow [WTEL-6860] 

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/api/table.js
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue

feature: get array from column value string in form table, and use as fields for table API request [WTEL-6965] (https://webitel.atlassian.net/browse/WTEL-6965)
[WTEL-6965]: https://webitel.atlassian.net/browse/WTEL-6965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Form table headers [WTEL-6965]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue

in form table, and add snakeToCamel for headers [WTEL-7029] (https://webitel.atlassian.net/browse/WTEL-7029)
[WTEL-7029]: https://webitel.atlassian.net/browse/WTEL-7029?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: add empty array as default value for nestedPathToValue [WTEL-7029]

---

src/ui/modules/info-section/modules/client-info/modules/contact/store/contact.js

in LOAD_CONTACTS_BY_DESTINATON action [WTEL-7041] (https://webitel.atlassian.net/browse/WTEL-7041)
[WTEL-7041]: https://webitel.atlassian.net/browse/WTEL-7041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: change searchParams value for calls [WTEL-7041]

---

src/app/api/agent-workspace/endpoints/history/HistoryAPIRepository.js

(https://webitel.atlassian.net/browse/WTEL-7075)

fix: change params for HistoryAPIRepository.js [WTEL-7075]

---

src/ui/modules/work-section/modules/chat/chat-messaging/composables/useChatScroll.js

(https://webitel.atlassian.net/browse/WTEL-7136)

fix: change threshold for scroll to bottom button [WTEl-7136] 

---

package-lock.json
package.json
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue

(https://webitel.atlassian.net/browse/WTEL-7110)

feature: add snakeToCamel transformer to props.source in form table [WTEl-7110]

---

src/ui/modules/info-section/modules/processing/modules/reporting/components/the-reporting.vue

task: [https://webitel.atlassian.net/browse/WTEL-7412
to do:added argument :selected for v-model

[WTEL-7412][https://webitel.atlassian.net/browse/WTEL-7412] added argument :selected for v-model

---

package-lock.json
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-file/processing-form-file-line.vue
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-file/processing-form-file.vue

task: https://webitel.atlassian.net/browse/WTEL-7385
to do: update icon for form file

fix: update icon for form file [WTEL-7385]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/components/link-table-content.vue
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/scripts/tableEmptySymbol.js

(https://webitel.atlassian.net/browse/WTEL-7418)

fix: enhance link table content component to support single and multiple links [WTEL-7418]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/api/table.js
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue

(https://webitel.atlassian.net/browse/WTEL-7420)

fix: ensure data transformation is applied consistently in table processing [WTEL-7420]

---

src/ui/modules/info-section/components/the-agent-info-section.vue
src/ui/modules/info-section/modules/general-info/components/general-info-tab.vue

to do: fixed error when not agent and show information when change tabs

fix: fixed error when not agent and show information when change tabs [WTEL-7430]

---

src/ui/modules/info-section/components/the-agent-info-section.vue
src/ui/modules/info-section/modules/general-info/components/general-info-tab.vue

task: https://webitel.atlassian.net/browse/WTEL-7430
to do: show info when aggent info is loaded

fix: show info when aggent info is loaded[WTEL-7430]

---

.github/workflows/ui-sdk.update.yml

task: https://webitel.atlassian.net/browse/WTEL-7440
to do: added github action for update ui-sdk lib in package-loc

added github action for update ui-sdk lib in package-loc [WTEL-7440]

---

src/ui/modules/queue-section/modules/chat-queue/components/the-agent-chat-queue.vue

task: https://webitel.atlassian.net/browse/WTEL-5482
to do: added counter for close chat

feat:  added counter for close chat  [WTEL-5482]

---

package-lock.json
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/scripts/getNestedValue.ts

(https://webitel.atlassian.net/browse/WTEL-7421)

fix: handle zero as a valid value in nested value retrieval [WTEL-7421]

---

src/ui/modules/work-section/modules/chat/chat-messaging/chat-messaging.vue
src/ui/modules/work-section/modules/chat/chat-messaging/quick-replies/quick-replies.vue

(https://webitel.atlassian.net/browse/WTEL-7359)
(cherry picked from commit 8b1364f65d3f49f4448967c73292faf2989f2b34)

fix: improve quick replies transition and structure in chat messaging [WTEL-7359]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/components/number-table-content.vue

(https://webitel.atlassian.net/browse/WTEL-7421)

fix: update number-table-content to use computed property for value display [WTEL-7421]

---

src/ui/modules/queue-section/modules/chat-queue/components/the-agent-chat-queue.vue

task: https://webitel.atlassian.net/browse/WTEL-5482
to do: added counter close chat

Feat:  added counter close chat  [WTEL-5482]

---

package-lock.json

(https://webitel.atlassian.net/browse/WTEL-7421)

hotfix: update ui-sdk version to 25.8.78 in package-lock.json [WTEL-7421]

---

src/ui/modules/work-section/modules/_shared/components/lookup-item/history-lookup-item.vue

task: https://webitel.atlassian.net/browse/WTEL-5756
to do: fixed color a tag in context menu

fix: fixed color a tag in context menu [WTEL-5756]

---

src/app/mixins/infiniteScrollMixin.js
src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-table/processing-form-table.vue
src/ui/modules/queue-section/modules/call-queue/components/offline-queue/offline-queue-container.vue
src/ui/modules/work-section/modules/_shared/components/lookup-item-container/lookup-item-container.vue
src/ui/modules/work-section/modules/chat/chat-messaging/chat-history/the-chat-history.vue

to do: replaced other infinite to wt-intersection-observer with ui
task: https://webitel.atlassian.net/browse/WTEL-7513

fix: replaced other infinite to wt-intersection-observer with ui[WTEL-7513] 

---

src/ui/modules/work-section/modules/chat/chat-messaging/message/chat-message.vue

to do: fixed space in last voice message
task: https://webitel.atlassian.net/browse/WTEL-5879

fix: fixed space in last voice message [WTEL-5879] 

---

src/ui/modules/work-section/modules/chat/chat-messaging/message/chat-message.vue

to do:  fixed style for space in chat
task: https://webitel.atlassian.net/browse/WTEL-5879

fix:  fixed style for space in chat [WTEL-7571]

---

src/ui/modules/work-section/modules/_shared/components/lookup-item-container/lookup-item-container.vue

to do: added padding for trigger observer
task: https://webitel.atlassian.net/browse/WTEL-7513

fix: added padding for trigger observer [WTEL-7513] 

---

src/ui/modules/work-section/modules/chat/chat-messaging/components/scroll-to-bottom-btn.vue

to do:  fixed get correct color for counter block
task: https://webitel.atlassian.net/browse/WTEL-7604

fix:  fixed get correct color for counter block[WTEL-7604]

---

src/ui/modules/work-section/modules/call/components/call-footer.vue
src/ui/modules/work-section/modules/call/components/call-header.vue
src/ui/modules/work-section/modules/call/components/call-numpad/numpad.vue
src/ui/modules/work-section/modules/call/components/the-call.vue
src/ui/modules/work-section/modules/call/enums/CallTab.enum.ts

to do: added enum for call tabs, use for call components, added trigger when components show with keep-alive, and call function for focus when components show
task: https://webitel.atlassian.net/browse/WTEL-7669

fix: added enum for call tabs, use for call components, ad… [WTEL-7669]

---

package-lock.json
package.json
src/features/modules/call/call.js
src/ui/modules/work-section/modules/call/components/call-contacts/contacts/contact-lookup-item.vue

to do: send contact id when call with contact tab, update webitel-sdk for work new params
task: https://webitel.atlassian.net/browse/WTEL-7229

feat: send contact id when call with contact tab, update webitel-sdk for work new params [WTEL-7229](https://webitel.atlassian.net/browse/WTEL-7229)

---

src/features/modules/member/member.js
src/ui/modules/queue-section/modules/call-queue/components/offline-queue/offline-queue-container.vue

to do: added return for action with request for stop call load with composable
task: https://webitel.atlassian.net/browse/WTEL-7570

fix: added return for action with request for stop call load with composable [WTEL-7570](https://webitel.atlassian.net/browse/WTEL-7570)

---

src/ui/modules/info-section/modules/client-info/components/client-info-tab.vue
src/ui/modules/work-section/modules/call/components/call-contacts/call-contacts-container.vue

to do:  hidden contact when user didn't have call center license
task: https://webitel.atlassian.net/browse/WTEL-5869

fix:  hidden contect when user didn't have call center license [WTEL-5869]

---

src/ui/modules/info-section/modules/processing/modules/form/components/components/processing-form-file/processing-form-file.vue

to do: fixed show plural or singular translate for count attachment filtes
task: https://webitel.atlassian.net/browse/WTEL-7386

fix: fixed show plural or singular translate for count attachment filtes [WTEL-7386] 
